//! Broker passwords belong to the OS credential store, not to localStorage.
//!
//! Before this module the connect password was serialized into
//! `dropqtt_active_broker` and into every entry of `dropqtt_broker_profiles`, which
//! on Windows means plaintext JSON inside the WebView2 profile directory: anyone who
//! can read that folder can read the broker credentials. What is stored there now is a
//! random, meaningless reference; the secret itself goes to the platform store
//! (Credential Manager on Windows, Keychain on macOS, Secret Service on Linux).
//!
//! Three rules hold this together:
//!
//! - **The secret never comes back to JavaScript.** There is no "read" command: a
//!   reference is resolved inside the process that opens the socket, so the plaintext
//!   cannot be re-persisted by accident or printed by a debug statement in the UI.
//! - **A missing secret is an error, never an anonymous connect.** If a reference
//!   exists but the store cannot answer for it, connecting fails with a message that
//!   says what to do. Silently dropping the credential would produce a
//!   `bad username or password` from the broker, which reads like a network fault.
//! - **Error strings never carry the secret.** `keyring::Error::BadEncoding` renders
//!   the bytes it rejected, so every variant is mapped by hand; see `describe`.
//!
//! Every operation comes in two shapes: `*_with(store, …)`, which is given its store
//! and is what the tests exercise, and the plain name, which resolves the process
//! store and is what the commands and the connect path call.

use std::sync::{Arc, OnceLock, RwLock};

use serde::Serialize;

use crate::protocol::BrokerConfig;

/// Namespace for every credential this app writes, so nothing here can collide with
/// another application's entries or overwrite one by accident.
pub const SERVICE: &str = "DropQTT";

/// Probed with a read of a key that is never written; "no entry" means the store
/// answered, which is all the availability check needs to know.
const AVAILABILITY_PROBE: &str = "availability-probe";

/// What the UI stores in `BrokerConfig.secretRef`: an opaque id, generated by the
/// caller. Constrained so a hand-edited localStorage value cannot name an arbitrary
/// credential in the shared store.
fn valid_reference(reference: &str) -> bool {
    !reference.is_empty()
        && reference.len() <= 64
        && reference
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
}

/// The account name inside the `DropQTT` namespace. `broker:` is a prefix rather than
/// a separate service so future kinds (webhook headers, key passphrases) can share it.
pub fn account_of(reference: &str) -> Result<String, String> {
    if !valid_reference(reference) {
        return Err(
            "the credential reference is not a valid identifier; re-enter the password".to_string(),
        );
    }
    Ok(format!("broker:{reference}"))
}

#[derive(Debug, Clone, Serialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SecretStatus {
    /// False when the platform store could not be reached at all.
    pub available: bool,
    /// Whether this build was compiled against a real platform store. False means the
    /// dependency has no backend here, so nothing can be stored securely at all.
    pub supported: bool,
    /// Short, human-readable reason when either flag is false. Never contains a secret.
    pub reason: Option<String>,
}

/// A credential store. `Ok(None)` means "the store works and this reference has no
/// value"; `Err` means "the store could not answer", which callers must not confuse
/// with "no password".
pub trait CredentialStore: Send + Sync {
    fn get(&self, account: &str) -> Result<Option<String>, String>;
    fn set(&self, account: &str, value: &str) -> Result<(), String>;
    fn remove(&self, account: &str) -> Result<(), String>;
    /// False when this implementation cannot keep anything. Availability is a
    /// separate question from support.
    fn supported(&self) -> bool;
}

pub struct KeyringStore;

impl CredentialStore for KeyringStore {
    fn get(&self, account: &str) -> Result<Option<String>, String> {
        let entry = entry(account)?;
        match entry.get_password() {
            Ok(value) => Ok(Some(value)),
            Err(keyring::Error::NoEntry) => Ok(None),
            Err(error) => Err(describe(&error)),
        }
    }

    fn set(&self, account: &str, value: &str) -> Result<(), String> {
        let entry = entry(account)?;
        entry.set_password(value).map_err(|error| describe(&error))
    }

    fn remove(&self, account: &str) -> Result<(), String> {
        let entry = entry(account)?;
        match entry.delete_credential() {
            Ok(()) | Err(keyring::Error::NoEntry) => Ok(()),
            Err(error) => Err(describe(&error)),
        }
    }

    fn supported(&self) -> bool {
        // Cargo.toml gives each of these targets a real backend, and only those
        // targets. `keyring` itself would compile a silent in-process mock if a
        // feature set were ever dropped, so this mirrors that table rather than
        // trusting the crate to have picked one: an unsupported platform must report
        // unsupported, and the UI must then keep saying so instead of pretending.
        cfg!(any(
            target_os = "windows",
            target_os = "macos",
            target_os = "ios",
            target_os = "linux",
            target_os = "freebsd",
            target_os = "openbsd"
        ))
    }
}

fn entry(account: &str) -> Result<keyring::Entry, String> {
    keyring::Entry::new(SERVICE, account).map_err(|error| describe(&error))
}

/// `Error`'s own `Display` prints the rejected bytes for `BadEncoding` and passes the
/// backend's message through for the failure variants -- both are exactly what this
/// module exists to protect, and there is no way to know what a platform put in there.
/// So every variant is mapped to an authored string. Numeric limits are the only thing
/// quoted back, because those are counts rather than content.
fn describe(error: &keyring::Error) -> String {
    match error {
        keyring::Error::NoEntry => "no credential is stored under this reference".to_string(),
        keyring::Error::BadEncoding(_) => {
            "the stored credential is not valid UTF-8; overwrite it by re-entering the password"
                .to_string()
        }
        keyring::Error::TooLong(_, limit) => format!(
            "the credential is too long for the platform store (the limit here is {limit} characters)"
        ),
        keyring::Error::Invalid(_, _) => {
            "the platform store rejected this credential".to_string()
        }
        keyring::Error::Ambiguous(_) => {
            "several credentials share this reference in the platform store; re-enter the password"
                .to_string()
        }
        keyring::Error::PlatformFailure(_) => {
            "the system credential store failed; it may be locked or full".to_string()
        }
        keyring::Error::NoStorageAccess(_) => {
            "the system credential store could not be reached; it may need to be unlocked"
                .to_string()
        }
        // `Error` is `#[non_exhaustive]`, so a future variant must not become a leak.
        _ => "the system credential store rejected the request".to_string(),
    }
}

static STORE_OVERRIDE: RwLock<Option<Arc<dyn CredentialStore>>> = RwLock::new(None);
static DEFAULT_STORE: OnceLock<Arc<dyn CredentialStore>> = OnceLock::new();

pub fn store() -> Arc<dyn CredentialStore> {
    if let Ok(guard) = STORE_OVERRIDE.read() {
        if let Some(custom) = guard.as_ref() {
            return custom.clone();
        }
    }
    DEFAULT_STORE
        .get_or_init(|| Arc::new(KeyringStore) as Arc<dyn CredentialStore>)
        .clone()
}

pub fn resolve_with(backend: &dyn CredentialStore, config: &mut BrokerConfig) -> Result<(), String> {
    let Some(reference) = config.secret_ref.clone() else {
        return Ok(());
    };
    if config.password.as_deref().is_some_and(|p| !p.is_empty()) {
        // The draft the user just typed wins over the reference it is replacing.
        return Ok(());
    }
    let account = account_of(&reference)?;
    match backend.get(&account)? {
        Some(value) => {
            config.password = Some(value);
            Ok(())
        }
        None => Err(format!(
            "no password is stored for this broker (reference {reference}); re-enter it in Settings"
        )),
    }
}

/// Fill in `password` from the credential store when the config points at one.
pub fn resolve(config: &mut BrokerConfig) -> Result<(), String> {
    resolve_with(&*store(), config)
}

pub fn status_with(backend: &dyn CredentialStore) -> SecretStatus {
    if !backend.supported() {
        return SecretStatus {
            available: false,
            supported: false,
            reason: Some("this build has no platform credential store".to_string()),
        };
    }
    let account = format!("broker:{AVAILABILITY_PROBE}");
    match backend.get(&account) {
        Ok(_) => SecretStatus {
            available: true,
            supported: true,
            reason: None,
        },
        Err(reason) => SecretStatus {
            available: false,
            supported: true,
            reason: Some(reason),
        },
    }
}

pub fn status() -> SecretStatus {
    status_with(&*store())
}

/// Store a new password. An empty value is rejected rather than written: a stored
/// empty string would later read as "no password" in `resolve_with`, which is the one
/// confusion this module must not create.
pub fn put_with(backend: &dyn CredentialStore, reference: &str, value: &str) -> Result<(), String> {
    if value.is_empty() {
        return Err(
            "an empty password is not stored; clear the credential instead of blanking it".to_string(),
        );
    }
    backend.set(&account_of(reference)?, value)
}

pub fn put(reference: &str, value: &str) -> Result<(), String> {
    put_with(&*store(), reference, value)
}

pub fn delete_with(backend: &dyn CredentialStore, reference: &str) -> Result<(), String> {
    backend.remove(&account_of(reference)?)
}

pub fn delete(reference: &str) -> Result<(), String> {
    delete_with(&*store(), reference)
}

/// Distinguishes "never stored" from "cannot be read", so the UI can say which.
pub fn exists_with(backend: &dyn CredentialStore, reference: &str) -> Result<bool, String> {
    backend
        .get(&account_of(reference)?)
        .map(|value| value.is_some())
}

pub fn exists(reference: &str) -> Result<bool, String> {
    exists_with(&*store(), reference)
}

/// An in-memory store: the test double, and the shape any future non-platform
/// backend would take.
pub struct MemoryStore {
    entries: std::sync::Mutex<std::collections::HashMap<String, String>>,
}

impl MemoryStore {
    pub fn new() -> Self {
        Self {
            entries: std::sync::Mutex::new(std::collections::HashMap::new()),
        }
    }

    pub fn peek(&self, account: &str) -> Option<String> {
        self.entries.lock().unwrap().get(account).cloned()
    }
}

impl Default for MemoryStore {
    fn default() -> Self {
        Self::new()
    }
}

impl CredentialStore for MemoryStore {
    fn get(&self, account: &str) -> Result<Option<String>, String> {
        Ok(self.entries.lock().unwrap().get(account).cloned())
    }
    fn set(&self, account: &str, value: &str) -> Result<(), String> {
        self.entries
            .lock()
            .unwrap()
            .insert(account.to_string(), value.to_string());
        Ok(())
    }
    fn remove(&self, account: &str) -> Result<(), String> {
        self.entries.lock().unwrap().remove(account);
        Ok(())
    }
    fn supported(&self) -> bool {
        true
    }
}

/// Point the module-wide store at a test double. Test-only, so a shipping binary
/// cannot be redirected away from the platform store.
#[cfg(test)]
pub fn use_test_store(backend: Arc<dyn CredentialStore>) {
    *STORE_OVERRIDE.write().unwrap() = Some(backend);
}

#[cfg(test)]
mod tests {
    use super::*;

    fn config_with(reference: Option<&str>, password: Option<&str>) -> BrokerConfig {
        BrokerConfig {
            secret_ref: reference.map(str::to_string),
            password: password.map(str::to_string),
            ..BrokerConfig::default()
        }
    }

    #[test]
    fn a_reference_is_scoped_to_this_app() {
        assert_eq!(account_of("abc123").unwrap(), "broker:abc123");
    }

    #[test]
    fn a_hand_edited_reference_cannot_name_arbitrary_credentials() {
        let too_long = "x".repeat(65);
        for bad in ["", "with space", "../../other", too_long.as_str(), "ünïcøde"] {
            assert!(
                account_of(bad).is_err(),
                "accepted {bad:?} as a credential reference"
            );
        }
        assert!(account_of("a-b_C9").is_ok());
    }

    #[test]
    fn a_stored_password_reaches_the_config_that_points_at_it() {
        let backend = MemoryStore::new();
        put_with(&backend, "r1", "hunter2").unwrap();
        let mut config = config_with(Some("r1"), None);
        resolve_with(&backend, &mut config).unwrap();
        assert_eq!(config.password.as_deref(), Some("hunter2"));
        assert_eq!(backend.peek("broker:r1").as_deref(), Some("hunter2"));
    }

    #[test]
    fn a_freshly_typed_password_beats_the_reference_it_is_replacing() {
        let backend = MemoryStore::new();
        put_with(&backend, "r1", "old").unwrap();
        let mut config = config_with(Some("r1"), Some("new"));
        resolve_with(&backend, &mut config).unwrap();
        assert_eq!(config.password.as_deref(), Some("new"));
        assert_eq!(backend.peek("broker:r1").as_deref(), Some("old"));
    }

    #[test]
    fn a_missing_credential_is_an_error_and_not_an_anonymous_connect() {
        let backend = MemoryStore::new();
        let mut config = config_with(Some("gone"), None);
        let error = resolve_with(&backend, &mut config).unwrap_err();
        assert!(error.contains("re-enter"), "{error}");
        assert!(config.password.is_none(), "resolve invented a password");
    }

    #[test]
    fn a_config_without_a_reference_is_left_alone() {
        let backend = MemoryStore::new();
        let mut config = config_with(None, Some("plain"));
        resolve_with(&backend, &mut config).unwrap();
        assert_eq!(config.password.as_deref(), Some("plain"));
        let mut anonymous = config_with(None, None);
        resolve_with(&backend, &mut anonymous).unwrap();
        assert!(anonymous.password.is_none());
    }

    #[test]
    fn an_empty_password_is_never_stored() {
        let backend = MemoryStore::new();
        assert!(put_with(&backend, "r1", "").is_err());
        assert_eq!(backend.peek("broker:r1"), None);
    }

    #[test]
    fn deleting_a_reference_clears_it_and_is_idempotent() {
        let backend = MemoryStore::new();
        put_with(&backend, "r1", "x").unwrap();
        delete_with(&backend, "r1").unwrap();
        assert_eq!(backend.peek("broker:r1"), None);
        delete_with(&backend, "r1").unwrap();
        assert!(!exists_with(&backend, "r1").unwrap());
    }

    #[test]
    fn existence_distinguishes_absent_from_broken() {
        let backend = MemoryStore::new();
        assert!(!exists_with(&backend, "never").unwrap());
        struct Broken;
        impl CredentialStore for Broken {
            fn get(&self, _: &str) -> Result<Option<String>, String> {
                Err("locked".into())
            }
            fn set(&self, _: &str, _: &str) -> Result<(), String> {
                Err("locked".into())
            }
            fn remove(&self, _: &str) -> Result<(), String> {
                Err("locked".into())
            }
            fn supported(&self) -> bool {
                true
            }
        }
        assert!(exists_with(&Broken, "any").is_err());
        let report = status_with(&Broken);
        assert!(!report.available);
        assert!(report.supported);
        assert_eq!(report.reason.as_deref(), Some("locked"));
        // A broken store must stop a connect, not silently drop the credential.
        let mut config = config_with(Some("r1"), None);
        assert!(resolve_with(&Broken, &mut config).is_err());
    }

    #[test]
    fn the_status_probe_reads_and_never_writes() {
        let backend = MemoryStore::new();
        assert!(status_with(&backend).available);
        assert!(
            backend.peek("broker:availability-probe").is_none(),
            "the availability probe left a credential behind"
        );
    }

    #[test]
    fn every_platform_this_app_ships_on_claims_a_real_store() {
        // `keyring` answers happily from an in-process mock when a target has no
        // backend feature, so "the calls succeeded" is not proof of a vault. What this
        // can prove at compile time is that each shipped target claims support, which
        // is the Cargo.toml table read back as code. That the credential really lands
        // in the Windows Credential Manager is proven live, by seeing it in `cmdkey`
        // after a save -- and that a build with no backend says so is the test below.
        assert!(
            KeyringStore.supported(),
            "this target is not covered by the keyring feature table in Cargo.toml"
        );
    }

    #[test]
    fn an_unsupported_target_stops_at_status_rather_than_storing_in_thin_air() {
        struct KeyringStoreless;
        impl CredentialStore for KeyringStoreless {
            fn get(&self, _: &str) -> Result<Option<String>, String> {
                Err("no store".into())
            }
            fn set(&self, _: &str, _: &str) -> Result<(), String> {
                Err("no store".into())
            }
            fn remove(&self, _: &str) -> Result<(), String> {
                Err("no store".into())
            }
            fn supported(&self) -> bool {
                false
            }
        }
        // The shape a target with no platform store takes: status says so, and a
        // connect that needs the secret fails instead of going out anonymously.
        let report = status_with(&KeyringStoreless);
        assert!(!report.supported);
        assert!(!report.available);
        let mut config = config_with(Some("r1"), None);
        assert!(resolve_with(&KeyringStoreless, &mut config).is_err());
        assert!(config.password.is_none());
    }

    #[test]
    fn the_module_store_is_what_the_plain_functions_use() {
        // The wrappers are what the commands and the connect path call, so the routing
        // itself is worth one proof. This test is the only reader of the override, and
        // every other test here injects its own store, so they cannot interfere.
        let backend = Arc::new(MemoryStore::new());
        use_test_store(backend.clone());
        put("r9", "via-global").unwrap();
        assert!(exists("r9").unwrap());
        let mut config = config_with(Some("r9"), None);
        resolve(&mut config).unwrap();
        assert_eq!(config.password.as_deref(), Some("via-global"));
        assert_eq!(status(), SecretStatus { available: true, supported: true, reason: None });
        delete("r9").unwrap();
        assert!(!exists("r9").unwrap());
    }

    #[test]
    fn an_error_string_never_contains_the_secret() {
        let secret = "sup3r-s3cret-value";
        let cases = [
            keyring::Error::BadEncoding(secret.as_bytes().to_vec()),
            keyring::Error::PlatformFailure(format!("cannot open {secret}").into()),
            keyring::Error::NoStorageAccess(format!("{secret} is locked").into()),
            keyring::Error::TooLong(secret.into(), 512),
            keyring::Error::Invalid(secret.into(), secret.into()),
        ];
        for error in cases {
            let shown = describe(&error);
            assert!(!shown.contains(secret), "{shown}");
            assert!(!shown.is_empty());
        }
    }

    #[test]
    fn a_reference_travels_in_json_as_the_only_credential_field() {
        let json = serde_json::to_value(config_with(Some("r1"), None)).unwrap();
        assert_eq!(json["secretRef"], "r1");
        assert!(json.get("password").is_none() || json["password"].is_null());
    }
}
